name: CR2 - RangeMaker

on:
  workflow_run:
    workflows: ["CR1 - Extract IPS"]  # Name of the primary workflow
    types:
      - completed  # Trigger only when the primary workflow is completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        > files/iplist.txt
        python -m pip install --upgrade pip
        pip install ipaddress requests

    - name: Run Range Maker
      run: python chainreaction/rangemaker.py

    - name: Check for Changes
      id: changesrmaker
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
    - name: Commit changes
      if: steps.changesrmaker.outputs.changed == 'true'     
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add chainreaction/exrange.txt
        timestamp=$(TZ='Asia/Tehran' date)
        git commit -m "✅List updated ${timestamp}"
        git push
